### ISSUE TITLE
编辑路由规则无法提交

### ISSUE THREAD

**Issue by wl4ever** [gogo-easy/ngrAdminPortal#19]
![image](https://user-images.githubusercontent.com/58181999/71758653-b5256b80-2edd-11ea-8343-6a6bdfb5577c.png)
编辑一个已存在的路由规则后，点击提交后，页面无响应，无法提交。
报错如下：
![image](https://user-images.githubusercontent.com/58181999/71758674-e0a85600-2edd-11ea-8a6d-9ae19b95384a.png)

**Comment by Fijileijun** [comment]
fixed:c5677712 jacobs <jacobs_lei@163.com> on 2020-01-07 at 20:35

**Comment by wl4ever** [comment]
confirm fixed
